### ISSUE TITLE
Make it compatible with Android Studio

### ISSUE THREAD

**Issue by bubbleguuum** [kreiger/intellij-idea-statusbar-filename#1]
Hi,

Great plugin, works great on regular Intellij !

I wanted something like that for a while and even opened an issue a while ago
to add it as a feature but it was rejected:
 
https://youtrack.jetbrains.com/issue/IDEA-252302

It would be nice it was compatible with current stable Android Studio (Artic Fox 2020.3.1 Patch 4).

**Comment by kreiger** [comment]
Hi, my apologies! I didn't mean to ignore you, i never saw this issue. I have just uploaded v1.1 which should support Android Studio 2022.3 and IntelliJ IDEA 2022.3 and later.
It will be available when JetBrains' moderation team has checked the plugin, at most two days.

**Comment by bubbleguuum** [comment]
Hi,

Thank you for this ! I confirm it is working fine.
Very useful for minimal Android Studio / IDEA UI setups with only a status bar, so the filename of the current editor can be seen.
